In [37]:
import pandas as pd
import xgboost as xgb

In [39]:
df_data = pd.read_csv('dix.csv', names=['Date','SP500','DIX','GEX'], index_col='Date', parse_dates=True, header=0)

def process_data(df):
    cols = df.columns
    for col in cols:
        df[col + ' %dif'] = df_data[col].pct_change()

    df['SP500 %mvmt'] = df['SP500 %dif'].shift(periods=-1)
    
    return df

df_data = process_data(df_data)
df_data

,SP500,DIX,GEX,SP500 %dif,DIX %dif,GEX %dif,SP500 %mvmt
Date,,,,,,,
2011-05-02,1361.219971,0.378842,1.897313e+09,NaN,NaN,NaN,-0.003379
2011-05-03,1356.619995,0.383411,1.859731e+09,-0.003379,0.012060,-0.019808,-0.006855
2011-05-04,1347.319946,0.392122,1.717764e+09,-0.006855,0.022719,-0.076337,-0.009070
2011-05-05,1335.099976,0.405457,1.361864e+09,-0.009070,0.034008,-0.207188,0.003820
2011-05-06,1340.199951,0.418649,1.490329e+09,0.003820,0.032535,0.094330,0.004544
...,...,...,...,...,...,...,...
2020-03-31,2584.590000,0.497417,-1.482108e+08,-0.016013,0.052199,-2.502844,-0.044142
2020-04-01,2470.500000,0.511401,-7.728500e+08,-0.044142,0.028114,4.214531,0.022829
2020-04-02,2526.900000,0.485221,-5.073984e+08,0.022829,-0.051192,-0.343471,-0.015137
2020-04-03,2488.650000,0.506475,-4.630797e+08,-0.015137,0.043802,-0.087345,0.070331
2020-04-06,2663.680000,0.446698,1.555165e+09,0.070331,-0.118026,-4.358309,NaN